version: 1
formatters:
  simple:
    format: '%(asctime)s %(module)s:%(lineno)d [%(levelname)s] %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  bot_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/bot.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
  steam_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: logs/steam_api.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8
loggers:
  bot_logger:
    level: DEBUG
    handlers: [bot_handler]
  steam_logger:
    level: DEBUG
    handlers: [steam_handler]
root:
  level: INFO
  handlers: [console]